### ISSUE TITLE
Updates as per latest API

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/cvemap#18]
```[tasklist]
### Tasks
- [x] Integrate new production API (https://cve.projectdiscovery.io)
- [x] Add interactive `-auth` cli option similar to nuclei to configure API key / env support
- [x] Add cli option for search `-q, -search string         search in cve data`
- [x] Update `-limit` option to respect result pagination
- [x] Make use of `?fields` option to only return required fields data.
```

**Note**: new api is almost same as before with more control over response.
